name: workflow-01
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_Name: "java application"
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout from main branch
        uses: actions/checkout@v6
      - name: upload-artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          name: source code artifact
          path: .
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v7.0.0
        with:
          name: source code artifact
          path: .
      - name: build java code
        run: mvn clean install

  printingappname:
    runs-on: ubuntu-latest
    steps:
        - name: printing application name 
          run: echo "app name is ${{ env.APP_Name }} or ${{vars.APP_Name}} and my password is ${{secrets.PASS_WORD }}"
      
